# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

install:
- R -e 'install.packages("remotes")'
- R -e 'remotes::install_deps(dep = T)'
- R -e 'remotes::install_local()'
- Rscript install.R

script:
- Rscript -e 'testthat::test_dir("tests/testthat/", reporter = c("progress", "fail"))'

after_failure:
- Rscript py_install_test.R

matrix:
  include:
  - os: linux
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="default"
  - os: linux
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="nightly"
  - os: linux
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="1.14.0"
  - os: linux
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="2.0.0-b0"
  - os: linux
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="default"
  - os: linux
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="nightly"
  - os: linux
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="1.14.0"
  - os: linux
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="2.0.0-b0"
  - os: linux
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="https://files.pythonhosted.org/packages/d2/ea/ab2c8c0e81bd051cc1180b104c75a865ab0fc66c89be992c4b20bbf6d624/tensorflow-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl"
  - os: linux
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="https://files.pythonhosted.org/packages/77/63/a9fa76de8dffe7455304c4ed635be4aa9c0bacef6e0633d87d5f54530c5c/tensorflow-1.13.1-cp36-cp36m-manylinux1_x86_64.whl"
  - os: osx
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="default"
  - os: osx
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="nightly"
  - os: osx
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="1.14.0"
  - os: osx
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="2.0.0-b0"
  - os: osx
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="default"
  - os: osx
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="nightly"
  - os: osx
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="1.14.0"
  - os: osx
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="2.0.0-b0"
  - os: osx
    env: INSTALL_METHOD="virtualenv" TENSORFLOW_VERSION="https://files.pythonhosted.org/packages/89/33/8617196404b6bbdd7d8a4c4fad0a2b28c81cfdb63786ce70800778d8e72d/tensorflow-1.13.1-cp27-cp27m-macosx_10_11_x86_64.whl"
  - os: osx
    env: INSTALL_METHOD="conda" TENSORFLOW_VERSION="https://files.pythonhosted.org/packages/f6/7b/5ab19bac13810661ff9e2485811553f1dea9a5d611ce846345aed4766bbe/tensorflow-1.13.1-cp36-cp36m-macosx_10_11_x86_64.whl"


