# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

install:
- R -e 'install.packages("remotes")'
- R -e 'remotes::install_deps(dep = T)'
- R -e 'remotes::install_local()'
- R -e "Rscript install.R"

script:
- Rscript -e 'testthat::test_dir("tests/testthat/")'

env:
  - TENSORFLOW_VERSION="default" INSTALL_METHOD="conda"

os:
  - linux
  - osx

