# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

install:
- R -e 'remotes::install_deps(dep = T)'

script:
- R CMD build .
- Rscript tests/testthat.R
